### ISSUE TITLE
2月27开始微信同步不上去了

### ISSUE THREAD

**Issue by Songpenglei123** [huangshihai/mimotion#16]
接口运行一切正常，但是微信不更新了

**Comment by EEEugene** [comment]
一样，感觉凉了

**Comment by chenqs000** [comment]
是的，但是新注册的邮箱账号能正常同步，可惜邮箱登录的api不知道要怎么改，目前只能先用着别人的小程序

**Comment by EEEugene** [comment]
> 



> 是的，但是新注册的邮箱账号能正常同步，可惜邮箱登录的api不知道要怎么改，目前只能先用着别人的小程序

小程序可以发一下吗

**Comment by chenqs000** [comment]
> > 
> 
> > 是的，但是新注册的邮箱账号能正常同步，可惜邮箱登录的api不知道要怎么改，目前只能先用着别人的小程序
> 
> 小程序可以发一下吗

叫【满目云盒】 不过要按他说的步骤看广告才能用

**Comment by huangshihai** [comment]
使用邮箱登录，已修改程序支持邮箱登录
