### ISSUE TITLE
方便留个联系方式吗？

### ISSUE THREAD

**Issue by alantam818** [huangshihai/mimotion#17]
请教您一些问题，微信alantam818

**Comment by KirkPan** [comment]
Traceback (most recent call last):
  File "/Users/mimotion/main.py", line 13, in <module>
    open_get_weather = sys.argv[3]
IndexError: list index out of range

请教一下，怎么解决？

**Comment by huangshihai** [comment]
> Traceback (most recent call last): File "/Users/mimotion/main.py", line 13, in open_get_weather = sys.argv[3] IndexError: list index out of range
> 
> 请教一下，怎么解决？

参考这个#5
