### ISSUE TITLE
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-python@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.   

### ISSUE THREAD

**Issue by lupingW** [huangshihai/mimotion#18]
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-python@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.   

不能跑呀

**Comment by rapon233** [comment]
遇到同样问题，怎么解决的啊？

**Comment by lupingW** [comment]
> 遇到同样问题，怎么解决的啊？

看一下我的仓库 https://github.com/lupingW/MImotion

**Comment by rapon233** [comment]
> > 遇到同样问题，怎么解决的啊？
> 
> 看一下我的仓库 https://github.com/lupingW/MImotion

哈哈研究了一下更新了version，谢谢啦 就是天气设置还有点额问题，我在研究研究
