### ISSUE TITLE
步数已经刷入Zepp Life，但是同步不到支付宝运动

### ISSUE THREAD

**Issue by zhiqiangss** [huangshihai/mimotion#26]
python3 main.py user@qq.com password false false

执行main.py后的返回结果：
---------------------------------------------------------
已设置为随机步数(24500~28000)
[2023-09-01 07:07:50]
账号：nic****qq.com
修改步数（27325）[success]

ZeppLife截图：
---------------------------------------------------------
![1451693496572_ pic](https://github.com/huangshihai/mimotion/assets/111512211/ea169cf1-a077-41ab-a7c3-8b8b6dad278a)

版本信息：
---------------------------------------------------------
ios版本： 16.6    
支付宝：10.3.80
ZeppLife：6.8.0 （内核版本：2.11.00）

反复清除了数据、重新绑定了也不行，请问是哪里的问题？

**Comment by huangshihai** [comment]
这个是账号的问题，需要重新注册账号，建议使用模拟器进行注册
