### ISSUE TITLE
接口失效了

### ISSUE THREAD

**Issue by NUPIGM** [huangshihai/mimotion#3]
关于获取时间的api:[http://time1909.beijing-time.org/time.asphttp://time1909.beijing-time.org/time.asp]失效了，connection timeout 连接超时了。

**Comment by matocool** [comment]
url = r'https://www.beijing-time.org/t/time.asp'

**Comment by NUPIGM** [comment]
> url = r'https://www.beijing-time.org/t/time.asp'
