### ISSUE TITLE
重新注册了一个邮箱账号，绑定了wx公众号，数据没同步

### ISSUE THREAD

**Issue by liucx1201** [huangshihai/mimotion#38]
新注册了一个邮箱账号，绑定了wx公众号，wx运动数据没同步，小米运动zepp 是更新，请问有什么解决方法吗？

**Comment by liucx1201** [comment]
@huangshihai 大佬脚本是跑成功了，就是数据同步wx有问题

**Comment by liucx1201** [comment]
111

**Comment by liucx1201** [comment]
找到方法了 关闭

**Comment by DLspark** [comment]
@liucx1201 能问下怎么解决的吗，我这边也是同样的问题，不同步到wx运动上
