### ISSUE TITLE
麻烦问一下，可以出一个可以在青龙面板上运行的python脚本嘛

### ISSUE THREAD

**Issue by mark-ch-mj** [huangshihai/mimotion#6]
麻烦问一下，可以出一个可以在青龙面板上运行的python脚本嘛，谢谢啦

**Comment by huangshihai** [comment]
不好意思，本项目主要是自用，暂时不考虑出其他平台的版本，Python本身就是跨平台的语言，理论上是可以直接在你所说的面板上运行的
