### ISSUE TITLE
失效了，微信 步数刷不上去

### ISSUE THREAD

**Issue by 1615758806** [huangshihai/mimotion#9]
截止今天，程序运行一切正常，但是微信不上步数，因此，我改了github token值，重新运行，但是小米运动步数和微信运动步数还是上不去

**Comment by apgk** [comment]
刚测试了下正常了，应该是华米接口问题

**Comment by 1615758806** [comment]
ok,谢谢了，已经正常

**Comment by sundys** [comment]
邮箱注册的账号没法登陆,貌似华米现在注册只能邮箱了

**Comment by apgk** [comment]
> 登陆,貌似华米现在注册只能邮箱了

邮箱的话看这个 https://github.com/wearehere8/mimotion-for-email
然后重新解绑再次绑定到支付宝微信去（重新授权）

**Comment by crmsci** [comment]
支付宝同步不上去

**Comment by huangshihai** [comment]
已支持邮箱登录
